CATALOGUE_HOST: catalogue.backend-{{ env }}.bharath2103.online
USER_HOST: user.backend-{{ env }}.bharath2103.online
CART_HOST: cart.backend-{{ env }}.bharath2103.online
SHIPPING_HOST: shipping.backend-{{ env }}.bharath2103.online
PAYMENT_HOST: payment.backend-{{ env }}.bharath2103.online