CART_HOST: cart.backend-{{ env }}.bharath2103.online
USER_HOST: user.backend-{{ env }}.bharath2103.online
RABBITMQ_HOST: rabbitmq-{{ env }}.bharath2103.online
RABBITMQ_USER: roboshop
RABBITMQ_PASSWORD: roboshop123